config/routes.rb
Rails.application.routes.draw do

  mount ForestLiana::Engine => '/forest'
  ActiveAdmin.routes(self)

  scope '(:locale)', locale: /fr|en/ do
    get 'static_pages/about'
    get 'static_pages/help'
    get 'static_pages/home'
    get 'static_pages/terms_and_conditions'
    get 'static_pages/cookies_policy'
    get 'static_pages/legal_notices'
    get 'static_pages/how_it_works'

    as :user do
        patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
    end
    devise_for :users, :controllers => {
      :confirmations => "confirmations",
      :registrations => "registrations"
    }

    resources :firms, only: [ :index, :show ] do
      resources :reviews, only: [ :create]
    end

    resources :requested_firms, only: [ :update]

    post 'firms/geosearch', to: "firms#geosearch"

    resources :reviews, only: [ :edit, :update, :destroy, :index]

    resources :profiles, only: [ :edit, :update, :show ]

    root 'firms#index'
  end

end

app/views/shared/_email_for_forms.html.erb
<%= form.input :email,
      as: :fake,
      input_html: { value: user_signed_in? ? @user.email : nil,
                    placeholder: user_signed_in? ? @user.email : nil },
      label: label,
      hint: hint,
      hint_html: hint_html
%>

app/views/shared/_featured_post.html.erb
<div>
  <div class="comment-title"><%= "#{review.title}" %></div>
  <div class="comment-body"><%= "#{review.comment}" %></div>
</div>
<div>
  <%= t("by", default: "By ") %>
  <%= content_tag(:span, "#{Faker::Name.name}", class: "username") %>
  <%= t("pseudonym", default: ' (pseudonym)') %>
  <%= t('for_firm', default: ' for ') %>
  <%= link_to(content_tag(:span, "#{firmname}", class: "firmname"), firm_path(firmid)) %>, <%= l(review.updated_at, format: :short) %>
</div>

app/views/shared/_flash.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <% if flash[:alert] %>
        <div class="alert alert-info alert-dismissible alert-error" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[:alert] %>
        </div>
      <% elsif flash[:notice] %>
        <div class="alert alert-info alert-dismissible alert-success" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[:notice] %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <ul class="list-inline">
          <li>
            <%= link_to 'https://www.facebook.com/pages/SkanHer/1084512778243084', html_options = { class: "social-icons" } do %>
              <i class="fa fa-facebook pulse"></i>
            <% end %>
          </li>
          <li>
            <%= link_to 'https://twitter.com/', html_options = { class: "social-icons" } do %>
              <i class="fa fa-twitter pulse"></i>
            <% end %>
          </li>
          <li>
            <%= link_to 'https://www.linkedin.com/company/skanher?trk=nav_account_sub_nav_company_admin', html_options = { class: "social-icons" } do %>
              <i class="fa fa-linkedin pulse"></i>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="col-xs-12 text-right">
        <p><%=t :footer_line_beginning %><%= link_to("The Choice! LLP", "#", html_options = { class: "clear" }) %></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_geo_search_form.html.erb
<div id="geoSearchFormWrapper">
  <%= form_tag(firms_geosearch_path, :method => "post", class: "navbar-form form-inline my-navbar-form",  id: "navbarSearchForm") do %>
    <%= text_field_tag :longitude, params[:search_longitude], class: "form-control my-navbar-form-control hidden", id: "longitudeSearch" %>
    <%= text_field_tag :latitude, params[:search_latitude], class: "form-control my-navbar-form-control hidden", id: "latitudeSearch" %>
    <button type="submit" class="btn btn-default hidden" id="navbarGeoSearchButton">
      <i class="fa fa-search"><%=t :geosearch_button_call_to_action %></i>
    </button>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-wagon" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only"><%= t(".toggle_navigation", default: "Toggle navigation") %></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag "logo-WF.png", class: "vertical-align-inline-block" %>
        <span class="brand-text vertical-align-inline-block"><span class='brandtext-first-part'>Women</span><span class='brandtext-second-part'>Friendly</span></span>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to t(:top_call_to_action, default: "Rate a firm"), firms_path, class: "btn btn-default" %>
        </li>


        <!--<li>-->
          <%#= link_to t(:top_call_to_action, default: "Rate a firm"), firms_path, class: "btn red-hover-btn" %>
        <!--</li>-->
        <% if user_signed_in? %>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-envelope-o"></i> <%= t(".messages", default: "Messages") %>
            <% end %>
          </li>
          <li class="dropdown">
            <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do %>
              <%= image_tag "http://placehold.it/30x30", class: "img-avatar" %>
              <%= t :profile, default: "Profile" %><span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t :sign_out, default: "Sign out" %>
                <% end %>
              </li>
              <li>
                <%= link_to edit_user_registration_path, method: :get do %>
                  <i class="fa fa-pencil-square-o"></i>  <%= t :update_connection_credentials, default: "Update your connexion credentials" %>
                <% end %>
              </li>
              <% if current_user.profile %>
                <li>
                  <%= link_to profile_path(current_user.profile), method: :get do %>
                    <i class="fa fa-list-alt"></i>  <%= t ".view_profile", default: "View your user profile" %>
                  <% end %>
                </li>
                <li>
                  <%= link_to edit_profile_path(current_user.profile), method: :get do %>
                    <i class="fa fa-bars"></i>  <%= t "update_profile", default: "Update your user profile" %>
                  <% end %>
                </li>
              <% end %>
              <li>
                <%= link_to reviews_path, method: :get do %>
                  <i class="fa fa-exclamation-triangle"></i>  <%= t "view_reviews", default: "View all your reviews" %>
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to t(:sign_in, default: "Sign in"), new_user_session_path, class: "btn btn-default" %>
          </li>
          <li>
            <%= link_to t(:sign_up, default: "Sign up"), new_user_registration_path, class: "btn btn-default" %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_navbar_alt.html.erb
<nav role="navigation" class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="#" class="navbar-brand">Brand</a>
    </div>
    <!-- Collection of nav links, forms, and other content for toggling -->
    <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#">Profile</a></li>
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">Messages <b class="caret"></b></a>
                <ul role="menu" class="dropdown-menu">
                    <li><a href="#">Inbox</a></li>
                    <li><a href="#">Drafts</a></li>
                    <li><a href="#">Sent Items</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Trash</a></li>
                </ul>
            </li>
        </ul>
        <form role="search" class="navbar-form navbar-left">
            <div class="form-group">
                <input type="text" placeholder="Search" class="form-control">
            </div>
        </form>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Login</a></li>
        </ul>
    </div>
</nav>

app/views/shared/_navbar_mobile_bottom.html.erb
<div id="bottomMobileNavBarContainer" class="container visible-xs-* hidden-sm hidden-md hidden-lg">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
      <div class="card-block shadowed-box">
        <!-- Do a new review -->
        <div class="row">
          <div col="col-xs-12">
            <%= button_to t(:top_call_to_action, default: "Rate a firm"), firms_path, method: :get, class: "btn btn-default btn-block red-hover-btn", type: "button"%>
          </div>
        </div>

        <!-- if the user is signed in -->
        <% if user_signed_in? %>
          <div class="row">
            <div col="col-xs-12">
              <%= button_to destroy_user_session_path, method: :delete, class: "btn btn-default btn-block regular-btn", type: "button" do %>
                <i class="fa fa-sign-out"></i>  <%= t :sign_out, default: "Sign out" %>
              <% end %>
            </div>
          </div>
          <div class="row">
            <div col="col-xs-12">
              <%= button_to edit_user_registration_path, method: :get, class: "btn btn-default btn-block regular-btn", type: "button" do %>
                <!-- TO DO update t parameter -->
                <i class="fa fa-pencil-square-o"></i>  <%= t :update_connection_credentials, default: "Update your credentials" %>
              <% end %>
            </div>
          </div>
          <div class="row">
            <div col="col-xs-12">
              <%= button_to reviews_path, method: :get, class: "btn btn-default btn-block regular-btn", type: "button" do %>
                <i class="fa fa-exclamation-triangle"></i><%= t "view_reviews", default: "View all your reviews" %>
              <% end %>
            </div>
          </div>
        <% else %>
          <div class="row">
            <div col="col-xs-12">
              <%= button_to t(:sign_up, default: "Sign up"), new_user_registration_path, method: :get, class: "btn btn-default btn-block", type: "button"%>
            </div>
          </div>
          <div class="row">
            <div col="col-xs-12">
              <%= button_to t(:sign_in, default: "Sign in"), new_user_session_path, method: :get, class: "btn btn-default btn-block", type: "button"%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
<div class="search-form-card-block">
  <%= form_tag(firms_path, method: "get", class: "form-inline") do %>
    <div class="input-group input-group-search-form">
      <%= search_field(:requested_firm, :name, class: "form-control my-navbar-form-control", placeholder: t(".placeholder", default: "Look for a firm")) %>
      <span class="input-group-btn">
        <button type="submit" class="btn btn-default btn-search-form"><i class="fa fa-search"></i></button>
      </span>
    </div><!-- /input-group -->
  <% end %>
</div>