config/routes.rb
Rails.application.routes.draw do

  mount ForestLiana::Engine => '/forest'
  ActiveAdmin.routes(self)

  scope '(:locale)', locale: /fr|en/ do
    get 'static_pages/about'
    get 'static_pages/help'
    get 'static_pages/home'
    get 'static_pages/terms_and_conditions'
    get 'static_pages/cookies_policy'
    get 'static_pages/legal_notices'
    get 'static_pages/how_it_works'

    as :user do
        patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
    end
    devise_for :users, :controllers => {
      :confirmations => "confirmations",
      :registrations => "registrations"
    }

    resources :firms, only: [ :index, :show ] do
      resources :reviews, only: [ :create]
    end

    resources :requested_firms, only: [ :update]

    post 'firms/geosearch', to: "firms#geosearch"

    resources :reviews, only: [ :edit, :update, :destroy, :index]

    resources :profiles, only: [ :edit, :update, :show ]

    root 'firms#index'
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :edit, :destroy]
  before_action :set_review, only: [:edit, :update, :destroy]

  def create
    set_firm
    # Error handling
    redirect_to firm_path(params[:firm_id]) and return if form_has_errors?
    # If no errors
    create_new_review
    send_mail_and_redirect_user
  end

  def show

  end

  def index
    set_user
    @reviews = @user.reviews

    @number_of_validated_reviews_for_user = @user.number_of_validated_reviews

    @pending_reviews = @user.pending_reviews
    @number_of_pending_reviews_for_user = @pending_reviews.count

    @published_reviews = @user.effectively_published_reviews
    @number_of_effectively_published_reviews_for_user = @published_reviews.count

    @pending_publication_reviews = @user.pending_publication_reviews
    @number_of_reviews_pending_publication_for_user = @pending_publication_reviews.count
  end

  def edit
    @firm = @review.firm

    variables_for_review_form
  end

  def update
    # The update method may be called by a click on:
    # - the validate button on the firm show view
    # - the validate button the review index view (user_pending_review partial)
    # - the validate button on the edit review view
    # It may also be called by clicks on the "flag" and "upvote"
    @firm = @review.firm
    update_type_switch
  end

  def destroy
    set_user
    @firm = @review.firm
    destroy_and_set_flash_notices
    redirect_to firm_path(@review.firm_id) if params[:controller] == "firms" || reviews_path if params[:controller] == "reviews"
  end

  private
    ####################
    # General purposes helpers methods
    def review_params
      params.require(:review).permit(:id, :firm_id, :confirmed_t_and_c, :comment, :title, :user_firm_relationship, :up_votes, :down_votes, answers_attributes: [:user_rating, :id]) if params[:review]
    end

    def set_firm
      @firm = Firm.find(params[:firm_id])
    end

    def set_user
      user_signed_in? ? @user = current_user : @user = User.find_or_create_by_email(email: params[:email])
    end

    def set_review
      @review = Review.find(params[:id])
    end
    ####################
    # update helpers methods
    def review_params_updater
      @updated_review_params = {updated_at_ip: request.remote_ip, validated: true}
      if review_params
        @updated_review_params.merge!(review_params.except(:answers_attributes))
        @updated_review_params[:answers_attributes] = review_params[:answers_attributes].values if review_params[:answers_attributes]
      end
    end

    def is_upvote_or_flag_update
      params[:upvoteButton] || params[:flagButton]
    end

    def set_upvote_or_flag_cookies
      cookies[:ufr_store] ? upvoted_or_flagged_reviews = JSON.parse(cookies[:ufr_store]) : upvoted_or_flagged_reviews = []
      upvoted_or_flagged_reviews << { review_id: @review.id, type: params[:upvoteButton] ? "upvoteButton" : "flagButton", date: Time.now }
      cookies.permanent[:ufr_store] = JSON.generate(upvoted_or_flagged_reviews)
    end

    def remove_upvote
      params[:upvoteButton] ? @review.up_votes -= 1 : @review.up_votes
      @review.save
    end

    def remove_flag
      params[:flagButton] ? @review.down_votes -= 1 : @review.down_votes
      @review.save
    end

    def remove_cookie
      updated_cookie_content = []
      @upvoted_or_flagged_reviews.each do | review |
        unless review["review_id"] == @review.id && ( (review["type"] == "upvoteButton" && params[:upvoteButton]) || (review["type"] == "flagButton" && params[:flagButton]) )
          updated_cookie_content << review
        end
      end
      cookies.permanent[:ufr_store] = JSON.generate(updated_cookie_content)
    end

    def remove_upvote_or_flag_switch(review)
      if review["type"] == "upvoteButton" && params[:upvoteButton]
        remove_upvote
        remove_cookie
      elsif review["type"] == "flagButton" && params[:flagButton]
        remove_flag
        remove_cookie
      else
        return false
      end
    end

    def check_if_review_already_touched
      @upvoted_or_flagged_reviews = JSON.parse(cookies[:ufr_store])
      @upvoted_or_flagged_reviews.each do | review |
        if review["review_id"] == @review.id
          remove_upvote_or_flag_switch(review)
          return false
        end
      end
      true
    end

    def cookie_agrees
      if cookies[:ufr_store]
        check_if_review_already_touched
      else
        true
      end
    end

    def upvote_or_flag_update_action
      if cookie_agrees
        params[:upvoteButton] ? @review.up_votes += 1 : @review.up_votes
        params[:flagButton] ? @review.down_votes += 1 : @review.down_votes
        @review.save
      end
    end

    def upvote_or_flag_review
      if upvote_or_flag_update_action
        set_upvote_or_flag_cookies
        respond_to do |format|
          format.html { redirect_to firm_path(@firm) }
          format.js
        end
      # else
       #  respond_to do |format|
       #    format.html { render 'firms/show' }
       #    format.js
       #  end
      end
    end

    def set_successfull_update_flash_message
      if ( @review.comment.present? || @review.title.present? )
        flash[:notice] = t(
          "review_validated_but_under_review",
          scope: [:controllers, :reviews, :update],
          firm_name: @firm.name,
          default: "Your review of #{@firm.name} has been validated. Our team is currently reviewing your comments before publication."
          )
      else
        flash[:notice] = t(
          "review_validated_and_published",
          scope: [:controllers, :reviews, :update],
          firm_name: @firm.name,
          default: "Your review of #{@firm.name} has been successfully validated. You can find it hereunder."
          )
      end
    end

    def set_failed_update_fash_message
      flash[:alert] = t(
          "review_validation_failure",
          scope: [:controllers, :reviews, :update],
          firm_name: @firm.name,
          default: "Your review of #{@firm.name} could not be validated."
          )
    end

    def user_validate_review
      authenticate_user!
      review_params_updater
      if @review.update(@updated_review_params)
        set_successfull_update_flash_message
        redirect_to firm_path(@firm)
      else
        set_failed_update_flash_message
        redirect_to edit_review_path(@review)
      end
    end

    def update_type_switch
      is_upvote_or_flag_update ? upvote_or_flag_review : user_validate_review
    end
    ####################
    # create helpers methods
    def has_valid_email
      unless EmailValidator.valid?(params[:email])
        flash[:alert] = t(
            :invalid_email,
            scope: [:controllers, :reviews, :create],
            default: "Please indicate a valid email address! "
            )
        @has_errors = true
      end
    end

    def has_at_least_one_vote
      if review_params[:answers_attributes] == {}
        flash[:alert] = t(
            :no_vote_on_any_criteria,
            scope: [:controllers, :reviews, :create],
            default: "Please vote on at least one criteria! "
            )
        @has_errors = true
      end
    end

    def has_confirmed_t_and_c
      if review_params[:confirmed_t_and_c] != "1"
        flash[:alert] = t(
            :conditions_not_accepted,
            scope: [:controllers, :reviews, :create],
            default: "Please accept the conditions of use of rating services!"
            )
        @has_errors = true
      end
    end

    def form_has_errors?
      @has_errors = false
      has_valid_email
      has_at_least_one_vote
      has_confirmed_t_and_c
      @has_errors
    end
    #######
    def set_flash_notice_and_send_mail(flash_variables)
      flash[flash_variables[:flash_type]] = flash_variables[:flash_message]
      yield
    end

    def i18n_flash_messages_store(flash_message_ref)
      flash_messages_hash = {
        review_successfully_saved_logged_user: t(
            :review_successfully_saved_logged_user,
            scope: [:controllers, :reviews, :create],
            firm_name: @firm.name,
            user_email: params[:email],
            default: "Dear #{params[:email]}, your review of #{@firm.name} has been successfully saved. It is currently pending. It still needs to be validated."
            ),
        review_successfully_saved_unlogged_user: t(
            :review_successfully_saved_unlogged_user,
            scope: [:controllers, :reviews, :create],
            firm_name: @firm.name,
            user_email: params[:email],
            default: "Dear #{params[:email]}, your review of #{@firm.name} has been successfully saved. Please check your emails at #{params[:email]} to validate it!"
            )
      }
      flash_messages_hash[flash_message_ref]
    end

    def send_mail_to_user
      if user_signed_in?
        set_flash_notice_and_send_mail(
          { flash_type: "notice",
            flash_message: i18n_flash_messages_store(:review_successfully_saved_logged_user)
          }) { ReviewMailer.new_review_for(params[:email], @firm).deliver_now }
        # flash[:notice] = t(
        #     :review_successfully_saved_logged_user,
        #     scope: [:controllers, :reviews, :create],
        #     firm_name: @firm.name,
        #     user_email: params[:email],
        #     default: "Dear #{params[:email]}, your review of #{@firm.name} has been successfully saved. It is currently pending. It still needs to be validated."
        #     )
        # ReviewMailer.new_review_for(params[:email], @firm).deliver_now
      else
        set_flash_notice_and_send_mail(
          { flash_type: "notice",
            flash_message: i18n_flash_messages_store(:review_successfully_saved_unlogged_user)

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_displayed_review_css_array.html.erb
<% @displayed_reviews_css_array = [
  "mad",
  "bad",
  "fine",
  "happy",
  "very-happy"
]
%>

app/views/reviews/_edit_review.html.erb
<h3 class="text-center"><%= t(".title", default: "Here are your votes pending validation for ") %><%= "#{@firm.name}" %>.</h3>
<p><%= t(".header_instruction", default: "Please review them carefully and update them, as the case may be.") %></p>
<% if @review.contains_sensitive_answers[:sensitive] %>
  <p class="review-warning"><%= "Beware! You have granted #{@review.contains_sensitive_answers[:count]} very bad #{"ranking".pluralize(@review.contains_sensitive_answers[:count])} to #{@firm.name}!" %></p>
  <p class="review-warning"><%= "At Skanher, we consider this kind of reviews as a serious case, both for you and for #{@firm.name}!" %></p>
  <p class="review-warning"><%= "Please read carefully our terms of service before validating your answers." %></p>
<% end %>
<p>
  <%= t(".press_button_instruction", default: "Once your are done, press the Validate button below.") %>
</p>
<hr>

<%= simple_form_for @review do |r| %>
  <%= render "reviews/review_form_master_content_validate", r: r %>
  <%= r.button :submit, "Validate", class: "btn-center" %>
<% end %>

app/views/reviews/_form_for_published_review.html.erb
<%= simple_form_for review, url: review_path(review), method: :patch, remote: true do |r| %>
  <div class="btn-group btn-group-justified" role="group" aria-label="flag-and-upvote-button-group">
    <div class="btn-group" role="group">
      <% flagButtonContent = t( ".flag_button_label", default: "Flag") %>
      <% flagButtonContent << " (#{review.down_votes})" if review.down_votes > 0 %>
      <%= r.button :submit, flagButtonContent, class: "btn btn-default", name: "flagButton" %>
    </div>
    <div class="btn-group" role="group">
      <% upvoteButtonContent = t( ".upvote_button_label", default: "Upvote") %>
      <% upvoteButtonContent << " (#{review.up_votes})" if review.up_votes > 0 %>
      <%= r.button :submit, upvoteButtonContent, class: "btn btn-default", name: "upvoteButton" %>
    </div>
  </div>
<% end %>

app/views/reviews/_individual_review_table.html.erb
<table class="table table-striped table-responsive table-individual-review">
  <tr>
    <td>
      <%= t("by", default: "By ") %><span class="username"><%= "#{Faker::Name.name}" %></span>
      <%= t("pseudonym", default: ' pseudonym') %>
      <%= t("for_firm", default: " for ") %>
      <%= link_to(content_tag(:span, "#{firmname}", class: "firmname"), firm_path(firmid)) %>, <%= l(review.updated_at, format: :short) %>
    </td>
  </tr>
  <% unless review.title.blank? && review.comment.blank? %>
    <tr>
      <td>
        <div class="comment-title"><%= review.title %></div>
        <div class="comment-body"><%= review.comment %></div>
      </td>
    </tr>
  <% end %>
  <% review.answers.reverse.each do | answer | %>
    <tr>
      <td>
        <div class="indiv-review-answers-wrapper">
          <div class="indiv-review-test-question"><%= t( :short_question, scope: [:tests_questions, :"question_#{answer.test_id}"], default: answer.test.test_question ) %></div>
          <div class="indiv-review-user-rating-icon <%= displayed_reviews_css_array[answer.user_rating - 1] %>"><%= answer.user_rating %></div>
          </div>
        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/reviews/_review_form_accept_t_and_c.html.erb
<%= r.input_field :confirmed_t_and_c, boolean_style: :inline, id: "confirmed_t_and_c", class: "cgu-checkbox my-hidden-class" %>
<label for="confirmed_t_and_c" class="form-bottom-fields cgu">
  <div class="row">
    <div class="col-xs-3 text-center">
      <i class="fa fa-check"></i>
    </div>
    <div class="col-xs-9">
      <p>
        <%= t ".t_and_c_confirmation_text", default: "I hereby confirm that I have read and agreed to the conditions of rating services of Skanher." %>
      </p>
    </div>
  </div>
</label>

<div>
  <div class="row">
    <div class="col-xs-3">
    </div>
    <div class="col-xs-9">
      <p>
        <%= link_to t(".read_t_and_c_link", default: "Read the Conditions of Rating Services"), static_pages_terms_and_conditions_path %>
      </p>
    </div>
  </div>
</div>
<hr/>

app/views/reviews/_review_form_answers.html.erb
<% user_rating_option_array = [] %>
<% @tests.fetch(a.index).select_options.split(";").each_with_index do |answer, i| %>
  <% user_rating_option_array << ["_", i + 1] %>
  <%# + 1 is here to fix minimum grade to 1 and maximum to 5 instead of 0 and 4 respect. %>
<% end %>

<%= a.input :user_rating,
    as: :radio_buttons,
    boolean_style: :inline,
    collection: user_rating_option_array,
    label: t( :short_question, scope: [:tests_questions, :"question_#{a.index + 1}"], default: "#{@tests.fetch(a.index).test_long_question}"),
    required: false,
    label_html: {
      class: "block"
      },
    wrapper_html: {
      class: "text-center my-rating-wrapper"
    },
    item_wrapper_class: "inline-block",
    input_html: {
      class: "rating-input my-hidden-input"
    },
    checked: params[:action] == 'show' && params[:controller] == 'firms' ? 3 : nil
  %>
<div class="vote-impact-wrapper" data-prior-answers-count='<%= @answer_count_by_test.fetch(a.index + 1) %>' data-prior-answers-total='<%= @total_by_test.fetch(a.index + 1) %>'>

    <table class="table table-striped table-responsive">
      <tr>
        <td>
          <%= t(".current_rating", default: "Current rating") %>
          <span class="badge"><%= @avg_ratings_by_test.fetch(a.index + 1).to_f.round(1) %></span>
          <span class="badge trend-badge">
            <% trend_arrow(a.index + 1) %>
            <i class="fa fa-long-arrow-up fa-lg <%= @css_class_for_arrow[@arrow_direction] %>"></i>
          </span>
        </td>
      </tr>

      <%  voting_stage_params_setter(a.index)
      %>
      <tr class="your-impact <%= @voting_stages[@current_stage][:css_hidden_switch] %>">
        <td>
          <%= @voting_stages[@current_stage][:text] %>
          <span class="badge average"><%= @voting_stages[@current_stage][:new_average_including_voter] %></span>
          <span class="badge trend-badge">
            <i class="fa fa-long-arrow-up fa-lg <%= @css_class_for_arrow[@voting_stages[@current_stage][:arrow_direction_including_voter]] %>"></i>
          </span>
        </td>
      </tr>
    </table>

</div>
<hr/>

app/views/reviews/_review_form_comments.html.erb
<div class="row">
  <div class="col-xs-12">
    <h5><%= t(".comment_action_sentence", firm_name: @firm.name, default: "Share your experience on %{@firm.name}") %></h5>
  </div>
  <div class="col-xs-12">
    <%= r.input :title, label: t(".title_label_for_review_comments", default: "Give a title to your experience (ex. This morning, when I came to the office...)") %>
  </div>
  <div class="col-xs-12">
    <%= r.input :comment, as: :text, input_html: { rows: 4 }, label: t(".comment_label_for_review_comments", default: "Describe your experience (ex. ... I was told that I had made an effort today. My boss was here and he did not react.)") %>
  </div>
</div>

app/views/reviews/_review_form_master_content_first_time.html.erb
<%= r.simple_fields_for :answers do |a| %>
  <%= render "reviews/review_form_answers", a: a %>
<% end %>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    window.load = setSensorsForRatings();
  <% end %>
<% end %>

app/views/reviews/_review_form_master_content_validate.html.erb
<%= r.simple_fields_for :answers, r.object.answers.order(:id) do |a| %>
  <%= render "reviews/review_form_answers", a: a %>
<% end %>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    window.load = setSensorsForRatings();
  <% end %>
<% end %>

app/views/reviews/_user_firm_relationship.html.erb
<div id="userFirmRelationshipGlobalWrapper">
  <% array_of_relationships = ["Employee", "CEO/COO", "Subcontractor", "Client", "Other"] %>

  <h4><%= t( ".user_firm_relationship_label", firm_name: @firm.name, default: "Please indicate your relationship with #{@firm.name}") %></h4>
  <p><%= t( ".user_firm_relationship_confidentiality_decla", default: "This information will remain confidential as per our terms of use of the ranking services.") %></p>
  <div>
  <% array_of_relationships.each do |relationship| %>
    <% normalized_relationship = relationship.sub(/\//,"").downcase %>
    <%= r.radio_button(
        :user_firm_relationship,
        "#{normalized_relationship}",
        id: "review_user_firm_relationship_#{normalized_relationship}",
        class: "my-hidden-class",
        checked: (@review.user_firm_relationship == normalized_relationship) || (params[:action] == 'show' && params[:controller] == 'firms' && relationship == "Employee")
        ) %>
    <label for=<%= "review_user_firm_relationship_#{normalized_relationship}" %> class="block form-bottom-fields user-firm-relationship">
      <div class="row vertical-align-middle">
        <div class="col-xs-3 text-center">
          <i class="fa fa-check"></i>
        </div>
        <div class="col-xs-9">
          <p class="button-label">
            <%= t ".#{normalized_relationship}", default: relationship %>
          </p>
        </div>
      </div>
    </label>
  <% end %>
  </div>
</div>

app/views/reviews/_validate_button_for_review.html.erb
<div class="btn-group" role="group">
  <%= simple_form_for review, url: review_path(review), method: :patch do |f| %>
    <%= button_tag(type: 'submit', class: "btn btn-default", id: 'validateReviewButton', form: "edit_review_#{review.id}") do %>
      <%= t( "validate_button_label", default: "Validate") %>
    <% end %>
  <% end %>
</div>

app/views/reviews/create.html.erb
<% content_for(:title, "Your Vote") %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
      <div class="row">
        <div class="col-xs-12">
          <div class="card-block shadowed-box">
            <h1 class="text-center">Thank you for your vote!</h1>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="card-block shadowed-box">
            <h3 class="text-center">A temporary account has been created for you. To validate your vote, please complete your profile.</h3>
            <p>These temporary credentials will remain valid for three days! After this delay, if you have not updated your profile, your vote will be discarded.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="card-block shadowed-box">
            <%= simple_form_for([@review, @user], url: review_user_path(@review, @user), html: { method: :patch }) do |f| %>
              <%= f.input :email, label: "Your username for this test." %>
              <%= f.error :email, id: 'user_name_error' %>
              <%= f.input :password, label: "Your password for this test." %>
              <%= f.full_error :token %>
              <%= f.button :submit, 'Update' %>
            <% end %>
            <div class="hidden">
              <div id="fakeUsername"><%= @user.email %></div>
              <div id="fakePassword"><%= @user.password %></div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="card-block shadowed-box">
            <h3 class="text-center">Here are your votes for <%= "#{@firm.name}" %>.</h3>
            <p>Please review them carefully and update them, as the case may be.</p>
            <% if @review.contains_sensitive_answers[:sensitive] %>
              <p class="review-warning"><%= "Beware! You have granted #{@review.contains_sensitive_answers[:count]} very bad #{"ranking".pluralize(@review.contains_sensitive_answers[:count])} to #{@firm.name}!" %></p>
              <p class="review-warning"><%= "At Sunny Rankings, we consider this kind of reviews as a serious case, both for you and for #{@firm.name}!" %></p>
              <p class="review-warning"><%= "Please read carefully our terms of service before validating your answers." %></p>
            <% end %>
            <p>Once your are done, press the Validate button below.</p>
            <hr>

            <%= simple_form_for @review do |r| %>
              <% @review.answers.each_with_index do |answer,i| %>
                <% i += 1 %>
                <%= simple_fields_for :answer[i] do |a| %>
                  <!-- actual input for each question. Default type is select in case javascript would not work -->
                  <%= a.input :user_rating,
                      label: "#{answer.test.test_long_question}",
                      wrapper_html: {
                        class: "text-center my-rating-wrapper",
                        "data-question-type" => "#{answer.test.positive_negative_switch}"
                      },
                      input_html: {
                        name: "user_rating[#{i}]",
                        id: "user_rating[#{i}]",
                        value: "#{answer.user_rating}",
                        "data-slider-min" => "1",
                        "data-slider-max" => "5",
                        "data-slider-step" => "1",
                        "data-slider-id" => "user_rating#{i}Slider",
                        "data-slider-value" => "#{answer.user_rating}",
                        "data-id" => "user_rating#{answer.test.id}"
                    } %>
                  <!-- javascript that creates the slider element on the input -->
                  <% content_for(:last_js) do %>
                    <%= javascript_tag do %>
                    $('[data-id=user_rating<%="#{i}"%>]').slider({
                        tooltip: 'hide',
                        handle: 'square'
                    });
                    <% end %>
                  <% end %>
                  <!-- True/False legend -->
                  <div class="containerForTrueFalse hidden">
                    <div class="containerForTrue subcontainers-for-true-false">True</div>
                    <div class="containerForFalse subcontainers-for-true-false">False</div>
                  </div>
                <% end %>
              <% end %>
              <!-- TO DO: Not very satisfactory way to select set the id of the firm; to be reviewed with a coach -->
              <p>By clicking the following button, you confirm that you are aware of the terms of Art. L. 323-2 of the French Criminal Code, pursuant to which any person introducing fraudulent data into a database is liable of a fine up to 75.000 euros and 5 years of custody.</p>
              <%= r.input :confirmed_t_and_c, label: "I hereby confirm that I have read and agreed to the conditions of use of the services of Sunny Rankings." %>
              <%= r.input :firm_id, as: :hidden, input_html: { value: "#{@firm.id}" } %>
              <%= r.button :submit, "Validate", class: "btn-center" %>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for(:last_js) do %>
  <%= javascript_tag do %>
    <!-- This line displays the True/False stuff -->
    $('.containerForTrueFalse').removeClass('hidden');
  <% end %>
<% end %>

app/views/reviews/edit.html.erb
<%# Very similar to the reviews/index/user_pending_review partial %>
<% content_for(:title,  t(".page_title", default: "Your Pending Review") ) %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
      <div class="row">
        <div class="col-xs-12">
          <div class="card-block shadowed-box">

            <h3 class="text-center"><%= t( ".heading_sentence", default: "Here is your latest pending review for ") + "#{@firm.name}" %>.</h3>
            <% default_for_instructions_html =
            "<p>Please review your votes carefully and update them, as the case may be.</p>
            <p>Once your are done, press the Validate button below.</p>"
            %>
            <%= t( ".instructions_html", default: default_for_instructions_html) %>
            <hr>

            <%# forms group %>

            <%# validate form %>
            <%= simple_form_for @review do |r| %>
              <%= r.error_notification %>
              <%= render "reviews/review_form_comments", r: r %>
              <%= render "reviews/review_form_master_content_validate", r: r %>
              <%= render "reviews/user_firm_relationship", r: r %>
            <% end %>

            <%# buttons group %>
            <hr/>
            <div class="btn-group btn-group-justified" role="group" aria-label="review-buttons-group">
              <%# discard form %>
              <%= render 'reviews/discard_button_for_review', review: @review %>
              <div class="btn-group" role="group">
                <%= button_tag(type: 'submit', class: 'btn btn-default', id: 'validateReviewButton', form: "edit_review_#{@review.id}") do %>
                  <%= t( "validate_button_label", default: "Validate") %>
                <% end %>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reviews/update.js.erb
<%# setting the target ids for the buttons where the number of flags or upvote should be displayed %>
<% target_id_flag = "#edit_review_#{@review.id} input[name=flagButton]" %>
<% target_id_upvote = "#edit_review_#{@review.id} input[name=upvoteButton]" %>
<%# setting the new content for the buttons (the nuw numbers of flags or upvotes) %>
<% flagButtonContent = t( ".flag_button_label", default: "Flag") %>
<% flagButtonContent << " (#{@review.down_votes})" if @review.down_votes > 0 %>
<% upvoteButtonContent = t( ".upvote_button_label", default: "Upvote") %>
<% upvoteButtonContent << " (#{@review.up_votes})" if @review.up_votes > 0 %>
<%# setting the content of the buttons %>
$("<%= target_id_flag %>").val("<%= flagButtonContent %>");
$("<%= target_id_upvote %>").val("<%= upvoteButtonContent %>");